name = "setsun-xyz"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]
main = "./.output/server/index.mjs"

[assets]
binding = "ASSETS"
directory = "./.output/public"

[[routes]]
pattern = "setsun.xyz"
custom_domain = true
